services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root            
      POSTGRES_PASSWORD: root
      POSTGRES_DB: games
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

      
volumes:
  pg-data:
